services:
  mongodb:
    image: mongo:6.0.8
    container_name: satyanaam-mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - satyanaam-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: satyanaam-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - satyanaam-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  satyanaam-backend:
    image: ghcr.io/04amanrajj/satyanaam-backend:v1.0.0
    container_name: satyanaam-backend
    restart: always
    environment:
      - PORT=4500
      - NODE_ENV=production
      - SECRET_KEY=myfoooooooood
      - ADMIN_SECRET_KEY=c59af9cc5322d2f1f1ad00e3c17332d6deb4000842917d2376a0eecc4a92e74f
      - JWT_EXPIRES_IN=6000
      - MAIL_SENDER=satyanamfood@gmail.com
      - GoogleKey=ieuqczkqrziieyim
      - MONGO_URI=mongodb://mongodb:27017/restaurent
      - REDIS_URI=redis://redis:6379
    networks:
      - satyanaam-net
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  satyanaam-frontend:
    image: ghcr.io/04amanrajj/satyanaam-frontend:v1.0.0
    container_name: satyanaam-frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - satyanaam-net
    depends_on:
      - satyanaam-backend

networks:
  satyanaam-net:
    name: satyanaam-net
    driver: bridge

volumes:
  mongodb-data:
    name: satyanaam-mongodb-data
  redis-data:
    name: satyanaam-redis-data
