# Single-stage heavyweight base image (Debian Bookworm ~1.1GB)
FROM node:20

# Run commands as root
WORKDIR /usr/src/app

COPY package*.json ./
# Install BOTH production and heavy devDependencies (Jest, TypeScript, etc)
RUN npm install

COPY . .

EXPOSE 3000
CMD ["node", "app.js"]
