global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # 1. Prometheus Internal Stats
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Node App Custom Exporter
  - job_name: 'node-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']

  # 3. cAdvisor Container Telemetry Exporter
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
