services:
  # ---------------------------------------------------
  # 1. CACHE NODE: High-speed Ephemeral Redis Caching
  # ---------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: redipoll-cache
    # No exposed ports on the host to protect the memory buffer internally
    networks:
      - redipoll-net
    restart: always

  # ---------------------------------------------------
  # 2. BACKEND API NODE: Express poll REST server
  # ---------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: redipoll-backend
    ports:
      - "5002:5000"
    environment:
      PORT: 5000
      REDIS_HOST: redipoll-cache
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - redipoll-net
    restart: always

  # ---------------------------------------------------
  # 3. FRONTEND static Nginx client visualizer
  # ---------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: redipoll-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - redipoll-net
    restart: always

# ---------------------------------------------------
# NETWORK BOUNDARY
# ---------------------------------------------------
networks:
  redipoll-net:
    driver: bridge
