services:
  # ---------------------------------------------------
  # 1. FRONTEND: Compiled React served by Nginx Gateway
  # ---------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portdock-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always

  # ---------------------------------------------------
  # 2. BACKEND: Fastify Server API
  # ---------------------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portdock-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/portdock
      - REDIS_URL=redis://redis:6379
    expose:
      - "5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  # ---------------------------------------------------
  # 3. DATABASE: PostgreSQL relantional engine
  # ---------------------------------------------------
  db:
    image: postgres:16-alpine
    container_name: portdock-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=portdock
    volumes:
      - portdock-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portdock"]
      interval: 3s
      timeout: 3s
      retries: 5
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: always

  # ---------------------------------------------------
  # 4. CACHE: Redis in-memory server
  # ---------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: portdock-redis
    volumes:
      - portdock-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    restart: always

volumes:
  portdock-db-data:
  portdock-redis-data:
